### PR TITLE
Dashes option and general options to cite edges

### PR DESCRIPTION
**Pull request by ThomasJorna**
Solves #147 to bring the same level of edge customization to the citation edges, plus provides a simpler variable which makes the citation edges dashes to further visually distinguish them from "normal".

```emacs-lisp
(setq org-roam-server-cite-edge-dashes t
      org-roam-server-extra-cite-edge-options (list (cons 'width 3))
```
yield what you would expect:

image

Should not break anything, as the code is exactly the same as the one for edges.

### CODE REVIEW

**Comment by thriveth** [comment]
Great idea!

**Comment by goktug97** [comment]
Hello, thank you for this feature! Unfortunately, doesn't work for me.
image
image

**Comment by ThomasJorna** [comment]
Hmmm that's very strange! I do remember getting this result as well, but I can't remember what caused it. Do you have any options set for cite edges?

**Comment by goktug97** [comment]
Nope, cloned your repository and started the server.

**Comment by ThomasJorna** [comment]
Ah I see what the problem is. It seems like it was a bug in `vis.js`. It claim to accept booleans or arrays for the "dashes" options, but does not seem to like `false` for some reason. I just added a rather ugly check for when `org-roam-server-extra-edge-options` is false, seemed to fix it.

**Comment by goktug97** [comment]
It works now, thank you. Can you update the doc string to pass `checkdoc`.

For example;
```elisp
(defcustom org-roam-server-cite-edge-dashes nil
  "When non-nil, change citation edges to dashes.
Changes edges that are created through org-roam-bibtex citations
to more easily distinguish them from other edges."
  :group 'org-roam-server
  :type 'boolean)
```

**Comment by ThomasJorna** [comment]
Done!

**Comment by goktug97** [comment]
Awesome!!

**Pull request merged**
